Repository react-lds/react-lds, pull requests merged in 2018-02, with the labels that each got.

#282 Revert "New Tabs implementation"
  src/components/Tab/Tab.js
  src/components/Tab/__tests__/Tab.spec.js
  src/components/Tab/index.js
  src/components/Tabs/ControlledTabs.js
  src/components/Tabs/Tab.js
  src/components/Tabs/TabLink.js
  src/components/Tabs/Tabs.js
  src/components/Tabs/__tests__/ControlledTabs.spec.js
  src/components/Tabs/__tests__/Tab.spec.js
  src/components/Tabs/index.js
  src/components/Tabs/utils.js
  src/index.js
  stories/Tabs.js
Labels: Priority: Critical, Type: Maintenance

#283 Add FocusTrap & Keyboard closing to Modal
  package.json
  src/components/Alert/Prompt.js
  src/components/Alert/__tests__/Prompt.spec.js
  src/components/Modal/Backdrop.js
  src/components/Modal/Modal.js
  src/components/Modal/ModalContent.js
  src/components/Modal/ModalFooter.js
  src/components/Modal/ModalHeader.js
  src/components/Modal/__tests__/Backdrop.spec.js
  src/components/Modal/__tests__/Modal.spec.js
  src/components/Modal/__tests__/ModalContent.spec.js
  src/components/Modal/__tests__/ModalFooter.spec.js
  src/components/Modal/__tests__/ModalHeader.spec.js
  src/components/Modal/index.js
  src/components/Modal/utils.js
  stories/Modal.js
  stories/Prompt.js
  stories/utils/decorators.js
  stories/utils/global.css
  yarn.lock
Labels: Type: Enhancement

#292 Carousel: only update panels if children actually changed
  src/components/Carousel/Carousel.js
Labels: Status: Review Needed, Type: Enhancement
