Repository react-lds/react-lds, pull requests merged in 2019-02, with the labels that each got.

#392 Support Spring'19 release
  package.json
  src/components/Alert/Alert.js
  src/components/Alert/__tests__/Alert.spec.js
  src/components/Breadcrumb/Breadcrumb.js
  src/components/Button/Base/Button.js
  src/components/Combobox/ComboboxDropdownListItem.js
  src/components/DataTable/defaultHeadRenderer.js
  src/components/Menu/MenuSubHeader.js
  src/components/Menu/__tests__/MenuSubHeader.spec.js
  src/components/Table/Row.js
  src/components/Table/__tests__/Row.spec.js
  src/components/VerticalNavigation/VerticalNavigationSection.js
  stories/Button.js
  yarn.lock
Labels: Priority: High, Type: Maintenance

#395 [next] Combobox improvements
  src/components/Combobox/AutoCompleteCombobox.js
  src/components/Combobox/BaseCombobox.js
  src/components/Combobox/EntityCombobox.js
  src/components/Combobox/__tests__/AutoCompleteCombobox.spec.js
  src/components/Combobox/__tests__/BaseCombobox.spec.js
  src/components/Combobox/__tests__/EntityCombobox.spec.js
  src/components/Combobox/components/ComboboxCore.js
  src/components/Combobox/components/ComboboxDropdown.js
  src/components/Combobox/index.js
  stories/Combobox/AsyncDemo.js
Labels: Status: In Progress

#396 Combobox improvements
  src/components/Combobox/AutoCompleteCombobox.js
  src/components/Combobox/BaseCombobox.js
  src/components/Combobox/EntityCombobox.js
  src/components/Combobox/components/ComboboxCore.js
  src/components/Combobox/components/ComboboxDropdown.js
  src/components/Lookup/Lookup.js
Labels: Status: In Progress

#402 Resolve Fragments in Buttongroup children
  package.json
  src/components/Button/ButtonGroups/ButtonGroup.js
  src/components/Button/ButtonGroups/__tests__/ButtonGroup.spec.js
  yarn.lock
Labels: Type: Enhancement

#400 v8.0.0
  .gitignore
  .npmignore
  CHANGELOG.md
  README.md
  package.json
  src/components/Combobox/AutoCompleteCombobox.js
  src/components/Combobox/BaseCombobox.js
  src/components/Combobox/Combobox.js
  src/components/Combobox/ComboboxDropdown.js
  src/components/Combobox/ComboboxDropdownList.js
  src/components/Combobox/ComboboxDropdownListItem.js
  src/components/Combobox/ControlledCombobox.js
  src/components/Combobox/EntityCombobox.js
  src/components/Combobox/__tests__/AutoCompleteCombobox.spec.js
  src/components/Combobox/__tests__/BaseCombobox.spec.js
  src/components/Combobox/__tests__/ComboboxCore.spec.js
  src/components/Combobox/__tests__/ComboboxDropdown.spec.js
  src/components/Combobox/__tests__/ComboboxDropdownList.spec.js
  src/components/Combobox/__tests__/ComboboxDropdownListItem.spec.js
  src/components/Combobox/__tests__/ComboboxListbox.spec.js
  src/components/Combobox/__tests__/ComboboxLists.spec.js
  src/components/Combobox/__tests__/ControlledCombobox.spec.js
  src/components/Combobox/__tests__/DropdownItems.spec.js
  src/components/Combobox/__tests__/EntityCombobox.spec.js
  src/components/Combobox/components/ComboboxCore.js
  src/components/Combobox/components/ComboboxDropdown.js
  src/components/Combobox/components/ComboboxDropdownLists.js
  src/components/Combobox/components/ComboboxListbox.js
  src/components/Combobox/components/DropdownItems/BaseDropdownItem.js
  src/components/Combobox/components/DropdownItems/DropdownItemCore.js
  src/components/Combobox/components/DropdownItems/EntityDropdownItem.js
  src/components/Combobox/components/DropdownItems/HeaderDropdownItem.js
  src/components/Combobox/components/DropdownItems/LoadingIndicatorDropdownItem.js
  src/components/Combobox/components/DropdownItems/SearchIndicatorDropdownItem.js
  src/components/Combobox/components/DropdownItems/index.js
  src/components/Combobox/components/index.js
  src/components/Combobox/index.js
  src/components/Combobox/utils/constants.js
  src/components/Combobox/utils/helpers.js
  src/components/Form/InputRaw.js
  src/components/Form/Picklist.js
  src/components/Form/PicklistDropdown.js
  src/components/Form/PicklistDropdownList.js
  src/components/Form/PicklistDropdownListItem.js
  src/components/Form/__tests__/Picklist.spec.js
  src/components/Form/__tests__/PicklistDropdown.spec.js
  src/components/Form/__tests__/PicklistDropdownList.spec.js
  src/components/Form/__tests__/PicklistDropdownListItem.spec.js
  src/components/Form/index.js
  src/components/Lookup/Lookup.js
  src/components/Spinner/SpinnerContainer.js
  stories/Combobox.js
  stories/Combobox/AsyncDemo.js
  stories/Combobox/AutoCompleteComboboxDemo.js
  stories/Combobox/BaseComboboxDemo.js
  stories/Combobox/constants.js
  stories/Combobox/index.js
  stories/Form.js
  stories/utils/helpers.js
  yarn.lock
Labels: Status: In Progress
